apiVersion: v1
kind: Pod
metadata:
  name: nginx     #name of the pod
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
